### ISSUE TITLE
To-do App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by lKori** [lKori/unit2-homework#1]
### 만들고자 하는 기능
- Todo 생성 기능
- Todo 수정 기능
- Todo 삭제 기능

### 해당 기능을 구현하기 위해 할 일
1. [ ] Todo 생성 시 DB에 저장 기능 구현
2. [ ] Todo 수정 시 DB에 수정 사항 저장 기능 구현
3. [ ] Todo 삭제 시 DB에서 삭제 기능 구현

### 예상 작업 시간
3h
